export const menu = [
  {
    category: "Hot Drinks",
    items: [
      { name: "شاي مقنن", price: 4500 },
      { name: "شاي بدره", price: 4000 },
      { name: "قهوة", price: 3000 },
      { name: "قهوة كبيرة", price: 4000 },
      { name: "هوت شوكليت", price: 7000 },
      { name: "أوفلتين", price: 6000 },
      { name: "نسكافيه", price: 7000 },
      { name: "شاي أحمر", price: 2500 },
      { name: "شاي أخضر", price: 2500 },
      { name: "نعناع", price: 2000 },
      { name: "زنجبيل", price: 2000 },
      { name: "بن الحموي صغير", price: 4500 },
      { name: "بن الحموي كبير", price: 5500 },
    ],
  },
  {
    category: "Iced Drinks",
    items: [
      { name: "سبانيش لاتيه (الأكثر مبيعاً)", price: 9000 },
      { name: "أيس كوفي ميكس", price: 7500 },
      { name: "أيس كوفي شوكلت", price: 6500 },
      { name: "أيس كوفي كراميل", price: 6500 },
      { name: "أيس كوفي أوريو", price: 7000 },
      { name: "كيان مقنن", price: 9000 },
      { name: "أيس تي", price: 7500 },
      { name: "أيس أوفلتين", price: 6000 },
    ],
  },
  {
    category: "Zalabia & Pastries",
    items: [
      { name: "صغيرة سادة", price: 4500 },
      { name: "صغيرة صوصات", price: 5700 },
      { name: "وسط سادة", price: 6500 },
      { name: "وسط صوصات", price: 7700 },
      { name: "كبيرة سادة", price: 9500 },
      { name: "كبيرة صوصات", price: 11000 },
      { name: "بسكويت يانسون (ثلاث قطع)", price: 3000 },
      { name: "بسكويت خبيز (أربع قطع)", price: 3000 },
      { name: "إضافة سكر", price: 1500 },
      { name: "إضافة عسل", price: 1500 },
    ],
  },
  {
    category: "Slush",
    items: [
      { name: "شغف مقنن (الأكثر مبيعاً)", price: 7500 },
      { name: "كيوي", price: 7000 },
      { name: "أناناس", price: 7000 },
      { name: "فراولة", price: 7000 },
      { name: "بلوبيري", price: 7000 },
      { name: "كرز", price: 7000 },
      { name: "ميكس", price: 7000 },
      { name: "أيس تي", price: 7000 },
      { name: "سلاش روز", price: 7000 },
      { name: "سلاش مانجو", price: 7000 },
    ],
  },
  {
    category: "Milkshake",
    items: [
      { name: " ميلك شيك أوريو (الأكثر مبيعاً)", price: 8500 },
      { name: "ميلك شيك فانيليا", price: 8500 },
      { name: "ميلك شيك كراميل", price: 8500 },
    ],
  },
  {
    category: "Mojito",
    items: [
      { name: "شغف مقنن (الأكثر مبيعاً)", price: 6500 },
      { name: "كيوي", price: 6000 },
      { name: "أناناس", price: 6000 },
      { name: "فراولة", price: 6000 },
      { name: "بلوبيري", price: 6000 },
      { name: "كرز", price: 6000 },
      { name: "ميكس", price: 6500 },
      { name: "موهيتو روز", price: 6000 },
      { name: "موهيتو مانجو", price: 6000 },
    ],
  },
];
